# Generated by Django 4.1.7 on 2023-03-16 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Region')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Zon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Zone')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.reg')),
            ],
        ),
        migrations.CreateModel(
            name='Wored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Woreda')),
                ('zon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.zon')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ServiceDeliveryOffice')),
                ('phone', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.nation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.reg')),
                ('woreda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.wored')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.zon')),
            ],
        ),
    ]
